# Generated by Django 5.2.4 on 2025-07-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
